
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import LoadingProvider from "./_contexts/LoadingContexts";
import { useEffect } from "react";
import { USER_TOKEN } from "@/utils/Instances";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Stellar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   const token = localStorage.getItem(USER_TOKEN);
  //   if (token) {
  //     redirect(`/stellar-intel/account`);
  //   }
  // }, []);

  return (
    <html lang="en">
      <Toaster position="top-center" />
      <body
        className={`w-full ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div  className="w-full">
          <LoadingProvider>{children}</LoadingProvider>
        </div>
      </body>
    </html>
  );
}
